### ISSUE TITLE
v:event should be copied, not referenced

### ISSUE THREAD

**Issue by justinmk** [cyansprite/Extract#1]
This code:

    autocmd TextYankPost * call extract#YankHappened(v:event)

should be changed to:

        autocmd TextYankPost * call extract#YankHappened(deepcopy(v:event))

because `v:event` is only available for the lifetime of the event, it is invalid as soon as any other event occurs. The only correct way to use it is to copy it, otherwise very weird things may happen. 

See `:help v:event`.

**Comment by cyansprite** [comment]
Thanks, will fix now.

**Comment by cyansprite** [comment]
Going to close with commit e9730da1dbd1de35361de09e8641d032fc0c6948
```vim
autocmd TextYankPost * call extract#YankHappened(deepcopy(v:event))
```
