### ISSUE TITLE
roxma/nvim-completion-manager support

### ISSUE THREAD

**Issue by xerron** [cyansprite/Extract#2]
I would like to have this plugin for NCM.

**Comment by cyansprite** [comment]
I will take a look at how to make a source

**Comment by cyansprite** [comment]
```vim
let g:extract_loadNCM = 1
```
@xerron Put this is your init.vim and let me know how it goes, if you run into any issues please let me know.

**Comment by davidosomething** [comment]
works for me! 👏 👏 👏

**Comment by xerron** [comment]
yes, works!
